### ISSUE TITLE
OAuth 2 url parameters

### ISSUE THREAD

**Issue by billybonks** [jaredhanson/passport-oauth2#14]
there currently isn't support for adding values to the URL parameters, when the oauth2 lib makes the initial oauth call

i would like to add access_type=offline for example

**Comment by jaredhanson** [comment]
This is handled by provider-specific subclasses that override `authorizationParams()`.  Every provider implements different params with non-standard options.  So, there's a way to do it.  What provider are you using?  It is probably already done, and if not can be easily added.

For example, here is the ones Facebook supports:
https://github.com/jaredhanson/passport-facebook/blob/master/lib/strategy.js#L98
