### ISSUE TITLE
Error: Unknown authentication strategy "oauth2"

### ISSUE THREAD

**Issue by C0DE-IN** [jaredhanson/passport-oauth2#149]
extends AuthGuard('oauth2')

the above line throws Error: Unknown authentication strategy "oauth2"

what could be the possible solution,
Iam using on nestjs with a generic oauth provider https://upstox.com/developer/api/v2/docs/#authorization

**Comment by acrtz** [comment]
@noiissyboy did you end up finding a solution for this?
