### ISSUE TITLE
Pass through response from server 

### ISSUE THREAD

**Issue by adamterlson** [jaredhanson/passport-oauth2#15]
In node-oauth, the changelog states the following:

```
0.9.7
OAuth2: Pass back any extra response data for calls to getOAuthAccessToken (Thanks to Tang Bo Hao)
```

This change is not respected/followed by passport-oauth2 in that these parameters are not plummed through to `_loadUserProfile` and other related functions.  Additional data passed back from the server beyond just the access token should be given to the user-controlled functions as well.

``` javascript
this._oauth2.getOAuthAccessToken(code, params,
  function(err, accessToken, refreshToken, params) {
    if (err) { return self.error(self._createOAuthError('Failed to obtain access token', err)); }

    self._loadUserProfile(accessToken, function(err, profile) { // <--- Should pass additional data
```

Happy to submit a pull request if this is deemed worth addressing!

**Comment by BrandonE** [comment]
It doesn't appear that this repository is still very active, but if that changes, it would be nice if these alternative callback signatures were documented in the README.
