### ISSUE TITLE
PKCE support

### ISSUE THREAD

**Issue by kh-pgodoy** [jaredhanson/passport-oauth2#157]
I have gone through https://medium.com/passportjs/pkce-support-for-oauth-2-0-e3a77013b278 and I understand it is supported, but based on the RFC
https://datatracker.ietf.org/doc/html/rfc7636#section-4.1 there these two parameters Code Verifier and Code challenge that are needed.
How is that used with the library?
Thanks!

**Comment by jaredhanson** [comment]
The library generates and includes the parameters automatically, as part of internal implementation.   The only thing required when using this library is setting `pkce: true` as an option.

**Comment by kh-pgodoy** [comment]
@jaredhanson cool, thanks for confirming!
