### ISSUE TITLE
needs updating

### ISSUE THREAD

**Issue by mainfraame** [jaredhanson/passport-oauth2#161]
I have a local branch that i'd like to push to this repo for review. It updates the repo to use typescript and follow all the modern practices; while not interfering with existing functionality and maintaining same tests.  Below is a list of the changes I've made:

* convert all files to typescript
* rename lib folder to src
* switch from mocha to jest for unit testing
* add prettier configuration
* switch jshint to eslint
* convert all prototype structures to classes
* rename files to match exports
* update tests to jest
* add depcheck
* remove makefile
* update travis config
* update gitignore to exclude dist
* add rollup-based build system using preppy
* update chai and chai passport

@jaredhanson can you add me to the repo so that i may push up this branch?

I created a forked repo to show you what i did:

https://github.com/mainfraame/passport-oauth2-fork

coverage:

<img width="1400" alt="Screen Shot 2022-06-19 at 8 08 57 PM" src="https://user-images.githubusercontent.com/5190439/174505574-cefa6464-a327-4648-bdad-129a30ad9983.png">

**Comment by jaredhanson** [comment]
Sorry, but I am not interested in maintaining these changes.
