### ISSUE TITLE
Resource parameter is missing in the authorization request. 

### ISSUE THREAD

**Issue by ronnross** [jaredhanson/passport-oauth2#18]
I'm attempting to authenticate against ADFS 3.0 OAuth2 provider. I'm receiving an error: 
`The resource parameter is missing in the authorization request. Send the resource parameter that contains the resource identifier's value.`
 I can't find a way in the passport-oauth2 strategy to pass additional parameters. 

I was able to fix this by adding an option:
`resource: EXAMPLE_CLIENT_SECRET`

and in the strategy.js I had to add:

`OAuth2Strategy.prototype.authorizationParams = function(options) {
  return { resource: options.resource};
};`

Problem I'm having is changing the strategy.js get's blow away during my CI deploy. Is there away to set this when creating a new OAuth2Strategy?

**Comment by jaredhanson** [comment]
Are you using a specific strategy that subclasses passport-oauth2?  If so, that'd be the strategy to extend with support for this option.

Closing this issue here.  Feel free to reopen it on the strategy that is more specific.
