### ISSUE TITLE
How to get id Token

### ISSUE THREAD

**Issue by turbo-xav** [jaredhanson/passport-oauth2#190]
const jwtPayLoad: IJwtPayload = {

        uid: userInfos.sub,

        mail: userInfos.email,

        firstName: userInfos.given_name,

        lastName: userInfos.family_name,

      };

 

      const authenticatedUser: Record<string, unknown> = { ...jwtPayLoad };

      return verifiedCallback(null, authenticatedUser);

    }

  }

}

`

 

I can get access_token, refresh_token but I can't get the Id_Token. I trier with params but it is void.

Is there a solution or a specific configuration to get it ?

 

Can you help me please ?

 

Thanks

**Comment by jaredhanson** [comment]
ID tokens are not part of OAuth 2.0, but rather an extension added by OpenID Connect.  You'll want to use the [`passport-openidconnect`](https://www.passportjs.org/packages/passport-openidconnect/) strategy.
