### ISSUE TITLE
Ability to specify response_type?

### ISSUE THREAD

**Issue by protobi** [jaredhanson/passport-oauth2#22]
integrating with Basecamp it generates this URL

`https://launchpad.37signals.com/authorization/new?response_type=code&redirect_uri=&client_id=MYCLIENTID`

which yields this response from Basecamp:

`:error: "Unsupported type: nil. We support user_agent and web_server."`

Is it possible to specify a different response type in Passport Oauth2?

**Comment by jaredhanson** [comment]
This should already be accommodated by the [passport-37signals](https://github.com/jaredhanson/passport-37signals) strategy.  If not, please reopen the issue there.
