### ISSUE TITLE
Pass all result data to stratety

### ISSUE THREAD

**Issue by shrimpywu** [jaredhanson/passport-oauth2#23]
when using windowslive strategy, we can only get back [limited set of data](https://github.com/jaredhanson/passport-windowslive/blob/master/lib/strategy.js#L35), token and profile. if we need the others, e.g "expires_in", passport didn`t pass thru. will be good if we can have all the data that come back from server

all data i mean
[param in this line of code](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L170)

**Comment by jaredhanson** [comment]
This form (https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L193) of the verify callback gives you all parameters, including "expires_in".
