### ISSUE TITLE
Question about oauth2 and user session

### ISSUE THREAD

**Issue by dendril** [jaredhanson/passport-oauth2#27]
Hey all,

I'm using this module to integrate with an OAuth 2.0 server. Everything works fine, but as part of the login, I want to simple store the `access_token` in the express session, and do not authenticate again till the token expires.

Which is the recommended way to handle this? Because I have read the code, and I didn't found a way to manage this in a clear way. Should I use 2 authentication strategies (first check in the session, and if the data is not present, just use the oauth2 strategy)?

Thanks in advance

**Comment by alexkahn** [comment]
Caching the session using something like [express-session](https://www.npmjs.com/package/express-session) should work just fine.

**Comment by dendril** [comment]
I forgot to close the issue. Finally found the solution by myself.

Thanks!
