### ISSUE TITLE
Getting AccessToken + RefreshToken + Profile back from an oAuth2 request

### ISSUE THREAD

**Issue by jascination** [jaredhanson/passport-oauth2#32]
My understanding of Passport callbacks is a little underdeveloped, so apologies in advance.

I'm trying to log in to Gmail using the `passport-oauth2` strategy. Here's my code:

```
passport.use(new OAuth2Strategy({
        authorizationURL: 'https://accounts.google.com/o/oauth2/auth',
        tokenURL: 'https://accounts.google.com/o/oauth2/token',
        clientID: configAuth.googleAuth.clientID,
        clientSecret: configAuth.googleAuth.clientSecret,
        callbackURL: configAuth.googleAuth.callback2
      },
      function(accessToken, refreshToken, profile, done) {
        process.nextTick(function() {
            console.log("Token is ");
            console.log(util.inspect(accessToken, false, null));
            
            console.log("Refresh is ");
            console.log(util.inspect(refreshToken, false, null));
            console.log("Profile is ");
            console.log(util.inspect(profile, false, null));
        });
      })
    );
```

This gives me:

```
Token is 
undefined
Refresh is 
{ access_token: '{an access token}',
  token_type: 'Bearer',
  expires_in: 3599,
  id_token:'{a really long string}' }
Profile is
{}
```

If I make the callback function the following

```
function(req, token, refreshToken, profile, done) {}
```

Then I get back:
```
Token is 
'{access token}'
Refresh is 
undefined
Profile is
{}
```

Any ideas on what I'm doing wrong here? Is the callback reliant on the order of objects being requested, like:

```
function(foo, bar, moo, mah){
  // foo = accesstoken
  // bar = refreshtoken
  // moo = profile
  // mah = done
}
```

Or does it just pass in whatever objects you call for (so order is not important?)

**Comment by Andargor** [comment]
I have the same issue, trying to connect to a Wordpress site with the WP Oauth Server plugin. THis plugin implements the <URL>/oauth/me?access_token=<token> function that can be used to retrieve the user information, but it seems that passport-oauth2 doesn't implement the userProfile function (in lib/strategy.js).

Can I somehow overload this private function to retrieve the userinfo? In test/oauth2.sub.userprofile.test.js, there looks like an example prototype for userProfile, I should use something like that to query the profile?

**Comment by jascination** [comment]
I found the solution to this actually - Google only gives you a `refreshToken` the first time a user authenticates with your app. You can see an SO thread about it here: http://stackoverflow.com/questions/10827920/google-oauth-refresh-token-is-not-being-received

So either the user needs to unauthenticate your account via their Google console, or you need to add `approval_prompt=force` to your passport routes, like so:

```
app.get('/auth/google', passport.authenticate('google', { 
   scope : 
      ['https://mail.google.com/', 'profile', 'email','https://www.googleapis.com/auth/userinfo.profile', 'https://www.google.com/m8/feeds'],
   accessType: 'offline', 
   approvalPrompt: 'force' 
  }
));
```

With `approvalPrompt: 'force'` it will return a refreshToken every time.
