### ISSUE TITLE
response_type is hardcoded to 'code'

### ISSUE THREAD

**Issue by klousiaj** [jaredhanson/passport-oauth2#36]
I'm working on a strategy for VisualStudioOnline and need to change the response_type for the Authenticate request.

According to their [documentation](https://www.visualstudio.com/en-us/integrate/get-started/auth/oauth) the request_type value needs to be 'Assertion' rather than 'code.' 

The base strategy set the params.response_type after the authorizationParams are provided so I don't see how I can set it without duplicating the entire method in my strategy. Am I missing something simple?

**Comment by jaredhanson** [comment]
This strategy implements support for standard `code` exchanges.  Any other type would have to be implemented as a separate strategy.

**Comment by jaredhanson** [comment]
I have no idea why Visual Studio is using assertion here.  They are not conforming to the spec at all.

**Comment by klousiaj** [comment]
Me either... there are a bunch of "features" like this I'm trying to overcome. Thanks for following up. I'll close this out.
