### ISSUE TITLE
dynamic authorizationUrl

### ISSUE THREAD

**Issue by smoebody** [jaredhanson/passport-oauth2#38]
flickr uses a so called `frob` that has to be included in the authorization request url. i think it has to be different for each authorization request, therefore it must be retrieved everytime the `authorizationUrl` is returned.
is there a convenient way to do so right now? if not, would it be possible to make the `authorizationUrl` option a function?

see [9.2 Not web-based applications](https://www.flickr.com/services/api/auth.spec.html#signing)

**Comment by VarunBatraIT** [comment]
+1

**Comment by simonmorley** [comment]
+1

**Comment by mirkods** [comment]
👍

**Comment by dfliess** [comment]
+1

**Comment by andan604** [comment]
An implementation of this can be found in a fork at https://github.com/theogravity/passport-oauth2-alt. If the authorizationURL is made dynamic, the tokenURL should be as well.
