### ISSUE TITLE
Using passport-oauth2 to gain OAuth2 support for Twitter auth

### ISSUE THREAD

**Issue by diegoaguilar** [jaredhanson/passport-oauth2#40]
As **`passport-twitter`** still goes for OAuth v1, I decided to try with **`passport-oauth2`** to accomplish Twitter login with out sessions for my app.

This is what I tried:

```
passport.use(new OAuth2Strategy({
    authorizationURL: 'https://api.twitter.com/oauth/authenticate',
    tokenURL: 'https://api.twitter.com/oauth/access_token',
    clientID: process.env.TWITTER_FINALCUT_CONSUMER_KEY,
    clientSecret: process.env.TWITTER_FINALCUT_CONSUMER_SECRET,
    callbackURL: 'http://localhost:9248/auth/login/redirect/tw'
    },
    function (access_token,refreshToken,profile,done) {
        console.log(accessToken,Object.keys(profile));
        return done(null, profile, {tokens: {accessToken: accessToken, refreshToken: refreshToken}});
}));
```

However when reaching the url for starting the auth process, I'm redirected to this Twitter screen. I can't figure out what's wrong with what I'm doing.

Any suggestions?

[![enter image description here](http://i.stack.imgur.com/3u95z.png)](http://i.stack.imgur.com/3u95z.png)

**Comment by trickeyd** [comment]
I am trying to do this now - did you manage it in the end?

Thanks

**Comment by diegoaguilar** [comment]
@trickeyd It's been 4 years since this ... Honestly I don't really remember how it went. Are you using Twitter as Auth provider or you want to consume Twitter API?

I'd suggest trying out Auth0 which works great, has a pretty good free tier and got Twitter as an social provider.

Otherwise (API consume) you can  use any JS library to which you should just pass a set of Twitter app keys.
