### ISSUE TITLE
The 'resource' parameter is missing in the authorization request.

### ISSUE THREAD

**Issue by dKab** [jaredhanson/passport-oauth2#45]
I'm trying to implement SSO (single sign on) using passport-oauth2 generic strategy. 

First I configure passport:

```
var passport = require('passport');
var OAuth2Strategy = require('passport-oauth2').Strategy;

passport.use('oauth2', new OAuth2Strategy({
      authorizationURL: 'provider/adfs/oauth2/authorize',
      tokenURL: 'provider/adfs/oauth2/token',
      clientID: 'my-id ,
      clientSecret: 'secret',
      callbackURL: 'https://localhost:44301/sso/consume'
    },
    function (accessToken, refreshToken, profile, done) {
      done(null, profile);
    }
));
```

then I specify 2 endpoints:

first:

```
app.get('/auth', passport.authenticate('oauth2'));
```

and second:

```
app.get('/sso/consume',
passport.authenticate('oauth2', { successRedirect: '/success', failureRedirect: '/fail' }));
```

And as it's said in passport docs I initialize passport:

```
app.use(passport.initialize());
```

The first round goes alright (I think) because browser gets redirected to my `callbackURL` ('sso/consume')

but on that page I see this error:

```
AuthorizationError: MSIS9601: The 'resource' parameter is missing in the authorization request.     Send the 'resource' parameter that contains the resource identifier's value.
   at OAuth2Strategy.authenticate (c:\epark\web-ui\node_modules\passport-oauth2\lib\strategy.js:126:25)
   at attempt (c:\epark\web-ui\node_modules\passport\lib\middleware\authenticate.js:348:16)
   at authenticate (c:\epark\web-ui\node_modules\passport\lib\middleware\authenticate.js:349:7)
  at Layer.handle [as handle_request] (c:\epark\web-ui\node_modules\express\lib\router\layer.js:95:5)
   at next (c:\epark\web-ui\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (c:\epark\web-ui\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (c:\epark\web-ui\node_modules\express\lib\router\layer.js:95:5)
   at c:\epark\web-ui\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (c:\epark\web-ui\node_modules\express\lib\router\index.js:330:12)
   at next (c:\epark\web-ui\node_modules\express\lib\router\index.js:271:10)
```

Do you know what is causing this issue?

**Comment by nmors** [comment]
Did you end up fixing this? Are you using AD FS 3.0 for your OAuth2 service? Is it Azure managed AD FS service, or self managed? 

I am facing the same issue, using win server 2012 R2 AD FS. I tried to even use this module, which has support for the resource parameter: https://github.com/University-Of-Cincinnati/passport-adfs-oauth

Maybe this other module will work for you.. AD FS is a bit special though. 

I tried specifying the resource, as per Relying Party Trust's identifier, but still not working

**Comment by anaganisk** [comment]
@dKab How did you solve this issue?

**Comment by eino-makitalo** [comment]
I read this and ended up to adding relaying party id xxx which is then that resource parameter.
https://blog.scottlogic.com/2015/03/09/OAUTH2-Authentication-with-ADFS-3.0.html

**Comment by aaditkamat** [comment]
For context to @eino-makitalo's answer, I managed to solve the same issue I had by specifying the right response parameter in the `authorizationURL` used in the `OAuth2Strategy` configuration i.e 'provider/adfs/oauth2/authorize?response=<RELAYING_PARTY_ID>' in place of just 'provider/adfs/oauth2/authorize'.

**Comment by stocks29** [comment]
I was having a similar issue where ADFS was not prompting for 2 factor auth before redirecting back to the application. The solution for me was to append the resource directly to the end of the `authorizationURL` in the `OAuth2Strategy` configuration:


```js
  passport.use(new OAuth2Strategy({
      authorizationURL: `https://fs.mycompany.com/adfs/oauth2/authorize?resource=${resource}`,
      tokenURL: 'https://fs.mycompany.com/adfs/oauth2/token',
      clientID: secrets.clientID,
      clientSecret: secrets.clientSecret,
      callbackURL: secrets.callbackURL,
      responseType: 'code id_token',
      scope: 'openid'
    },
```

I hope this helps someone.
