### ISSUE TITLE
Getting data from resources server by only the Authorization header with bearer token

### ISSUE THREAD

**Issue by kitlee** [jaredhanson/passport-oauth2#53]
Can I use the bearer token to retrieve data from resources server (some OAuth2 provider's resources server, let's name it "Foo Bar") with the same passport strategy directly?

Assume I have configured the following passport strategy in my web application:
```
passport.use('fooBar', new OAuth2Strategy(fooBarPassportConfig,
  function (req, accessToken, refreshToken, profile, done) {
    ...
  }
));
```
I want something like:
```
myApiRoute.use('/*', function (req, res, next) {
  passport.authenticate('fooBar')(req, res, next);
});
```
When HTTP request comes to `myApiRoute`, I first lookup my database to find who is it, then get his bearer token and go through the `fooBar` strategy to try to get the latest profile from Foo Bar, then I can access to `req.user` in my controllers and models.

I tried the above code, but no luck.

**Comment by jaredhanson** [comment]
Closing.  Not an issue with this project.  Questions about integrating authentication into a larger application should be asked in a discussion forum.
