### ISSUE TITLE
customHeaders option and default POST data conflict

### ISSUE THREAD

**Issue by SachaCR** [jaredhanson/passport-oauth2#58]
I have to use customHeaders to send a Authorization header during the getAccessToken call. 
this header contain base64 clien_id:client_secret.

It work very well and thanks for this usefull option. 

But the problem is that the OAuth2 server reject my request with a 403 because the parameters client_id and client_secret are sent in the post_data too.

Is there any way to avoid this behavior ?

I have see nothing in the source for this. Do you think this use case deserve to add a new options ?

**Comment by jaredhanson** [comment]
Can you provide an details for how you resolved this issue?  It will help others who encounter a similar problem.  Thanks.

**Comment by SachaCR** [comment]
The 403 was not due to the Post data. It was an error from myself in the headers. 
My bad sorry.
