### ISSUE TITLE
Passing state querystring without sessions

### ISSUE THREAD

**Issue by caub** [jaredhanson/passport-oauth2#71]
I saw the discussion https://github.com/jaredhanson/passport-facebook/issues/14 can a state querystring be passed without sessions? for providers like Google/Facebook

Is there a way to pass state informations (like the initial referer url) alongside the oauth2 flow?

**Comment by manuel-di-iorio** [comment]
+1

**Comment by caub** [comment]
you can pass a state in `passport.authenticate(<provider>, {scope: ['email'], state: 'foobar'})`

**Comment by samkelleher** [comment]
This solution doesn't actually work because while you can pass in a custom state, it will fail to validate against the session state that is called internally, and thus fail to validate.

**Comment by farleyschaefer** [comment]
Currently facing this issue. Is there any way around this? can I disable the express-session check?

**Comment by samkelleher** [comment]
In the end @farleyschaefer I actually didn't use passportjs at all and just implemented the oauth calls in vanilla js since it's nowdays simple and easy to do so. Passport hasn't received much update or support with some code untouched in over 5 years.
